matrix:
  include:
    - sudo: required
      language: node_js
      node_js:
        - "9"
      dist: trusty
      before_install:
        - sudo apt-get install -y realpath openjdk-8-jdk wine mono-complete gcc-multilib g++-multilib
      script: bash -c "CI=false scripts/build.sh"
      addons:
        apt:
          update: true
      before_deploy:
        - sudo apt-get install rsync sshpass
      deploy:
        provider: script
        script: bash scripts/travisDeploy.sh
        on:
          all_branches: true
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js:
        - "9"
      before_install:
        - brew update
        - brew outdated coreutils || brew upgrade coreutils
        - brew outdated maven || brew upgrade maven
        - brew install yarn --without-node
      script: bash -c "CI=false scripts/build.sh"
      deploy:
        provider: script
        script: bash scripts/travisDeploy.sh
        on:
          all_branches: true
