sudo: required
language: node_js
node_js:
  - "9"
dist: trusty
before_script:
  - sudo apt-get update
  - sudo apt-get install realpath
  - sudo apt-get install openjdk-8-jdk
script: bash -c "CI=false scripts/build.sh"
