matrix:
  include:
    - sudo: required
      language: node_js
      node_js:
        - "9"
      dist: trusty
      before_install:
        - wget -nc https://dl.winehq.org/wine-builds/Release.key
        - sudo apt-key add Release.key
        - sudo apt-add-repository -y https://dl.winehq.org/wine-builds/ubuntu/
        - sudo apt-get update
        - sudo apt-get install -y --install-recommends realpath openjdk-8-jdk winehq-stable mono-complete gcc-multilib g++-multilib
      script: bash -c "CI=false scripts/build.sh --windows"
      before_deploy:
        - sudo apt-get install rsync
      deploy:
        skip_cleanup: true
        provider: script
        script: bash scripts/travisDeploy.sh
        on:
          all_branches: true
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js:
        - "9"
      before_install:
        - brew update
        - brew outdated coreutils || brew upgrade coreutils
        - brew outdated maven || brew upgrade maven
        - brew install yarn --without-node
      script: bash -c "CI=false scripts/build.sh"
      deploy:
        skip_cleanup: true
        provider: script
        script: bash scripts/travisDeploy.sh
        on:
          all_branches: true
